name: Deploy to SKO Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Deploy to server
        run: |
          rsync -avz --delete ./ skons@172.19.152.52:/home/skons/gitpush/

      - name: Move files to web directory and restart Nginx
        run: |
          ssh skons@172.19.152.52 'sudo rsync -avz --delete /home/skons/gitpush/ /var/www/skons/ && sudo systemctl restart nginx'
